### ISSUE TITLE
Replicating results 

### ISSUE THREAD

**Issue by silvtal** [Xiaoyu2425/Ensemble-Quotient-Optimization#1]
Hi,
thank you for putting together the mEQO package and congrats on your very interesting publication

I tried to replicate your results for the replicate microbial microcosms dataset, your most simple one where you use a constant Y variable in order to find the functional Pseudomonadaceae and Enterobacteriaceae groups. It's interesting to me because I have a similar dataset where I think your method could be useful.

I'm trying to use the GA with an uniform Y constant. The thing is, I don't quite understand the parameters I should be using. The group I get is always either a group that contains all OTUs or a mixture of Enterobacteriaceae, Pseudomonadaceae and others. Plotting graphs is not very informative either. I'm trying to use the GA with an uniform constant.

Also, I'm using 99% OTUs instead of the ASVs, with relative abundance tables for their 92 final-transfer glucose samples. Which samples did you test exactly? I've also tried using the samples for all their transfers at once (350 or so) but the group I get with default parameters is also a mix.

I would be very grateful if you could guide me a bit on this matter. I apologize if you already clarified the parameters somewhere else, I just couldn't find it anywhere

Thanks,
Silvia

**Comment by Xiaoyu2425** [comment]
Hi, thank you for your interest in our work! Sorry for the delayed reply as I am traveling a lot recently.
Constant variable Y is a special scenario for EQO. We have to introduce additional constraint to avoid empty or full subsets, which are numerically perfect but ecologically trivial. This is to be specified by "amin" and "amax" in the current version of package, e.g., the final group should have minimal average relative abundance above 5% but less than 95%. Such threshold is somewhat arbitrary, but unfortunately that is the best I could think of now. 
Regarding the Goldfold et al 2018 microcosm data, we only used the 8 communities shown in their Figure 1G as a quick "sanity check". It should be noted that even with these simplest 8 samples, EQO still gets a mixture of Enteros and Pseudos. But ultimately, what matters is the number of reads (or total relative abundance of ASVs) rather than number of ASVs that are correctly coarse-grained. There are always ASVs that are very rare in relative abundance and only present in very few samples.
I hope these could help a bit and good luck to your research!

**Comment by silvtal** [comment]
Hi, your reply was actually fast, thanks!
I see, that makes sense. Using those samples and amin/amax values, I experimented a bit with selecting a minimal Nmax value and I got the same plot. I think I understand better now. Thank you!
